// ...existing code...
// Cleaned data file: INDONESIAN_DISTRICTS is exported without duplicates

// Source list (kept for readability) — final export will remove duplicates while preserving first occurrence order.
const _RAW_INDONESIAN_DISTRICTS = [
  // Aceh
  'Aceh Barat',
  'Aceh Barat Daya',
  'Aceh Jaya',
  'Aceh Selatan',
  'Aceh Singkil',
  'Aceh Tamiang',
  'Aceh Tengah',
  'Aceh Tenggara',
  'Aceh Timur',
  'Aceh Utara',
  'Banda Aceh',
  'Langsa',
  'Lhokseumawe',
  'Sabang',
  // Sumatera Utara
  'Asahan',
  'Batubara',
  'Dairi',
  'Deli Serdang',
  'Humbang Hasundutan',
  'Karo',
  'Labuhanbatu',
  'Labuhanbatu Selatan',
  'Labuhanbatu Utara',
  'Langkat',
  'Mandailing Natal',
  'Nias',
  'Nias Barat',
  'Nias Selatan',
  'Nias Utara',
  'Padang Lawas',
  'Padang Lawas Utara',
  'Pakpak Bharat',
  'Samosir',
  'Serdang Bedagai',
  'Simalungun',
  'Tapanuli Selatan',
  'Tapanuli Tengah',
  'Tapanuli Utara',
  'Toba Samosir',
  'Medan',
  'Binjai',
  'Pematangsiantar',
  'Sibolga',
  'Tanjungbalai',
  'Tebing Tinggi',
  // Sumatera Barat
  'Agam',
  'Dharmasraya',
  'Kepulauan Mentawai',
  'Lima Puluh Kota',
  'Padang Pariaman',
  'Pasaman',
  'Pasaman Barat',
  'Pesisir Selatan',
  'Sijunjung',
  'Solok',
  'Solok Selatan',
  'Tanah Datar',
  'Bukittinggi',
  'Padang',
  'Padangpanjang',
  'Pariaman',
  'Payakumbuh',
  'Sawahlunto',
  'Solok Kota',
  // Riau
  'Bengkalis',
  'Indragiri Hilir',
  'Indragiri Hulu',
  'Kampar',
  'Kepulauan Meranti',
  'Kuantan Singingi',
  'Pelalawan',
  'Rokan Hilir',
  'Rokan Hulu',
  'Siak',
  'Dumai',
  'Pekanbaru',
  // Jambi
  'Batang Hari',
  'Bungo',
  'Kerinci',
  'Merangin',
  'Muaro Jambi',
  'Sarolangun',
  'Tanjung Jabung Barat',
  'Tanjung Jabung Timur',
  'Tebo',
  'Jambi',
  'Sungai Penuh',
  // Sumatera Selatan
  'Banyuasin',
  'Empat Lawang',
  'Lahat',
  'Muara Enim',
  'Musi Banyuasin',
  'Musi Rawas',
  'Musi Rawas Utama',
  'Ogan Ilir',
  'Ogan Komering Ilir',
  'Ogan Komering Ulu',
  'Ogan Komering Ulu Selatan',
  'Ogan Komering Ulu Timur',
  'Palembang',
  'Prabumulih',
  'Lubuklinggau',
  // Bengkulu
  'Bengkulu Selatan',
  'Bengkulu Tengah',
  'Bengkulu Utara',
  'Kaur',
  'Kepahiang',
  'Lebong',
  'Mukomuko',
  'Rejang Lebong',
  'Seluma',
  'Bengkulu',
  // Lampung
  'Lampung Barat',
  'Lampung Selatan',
  'Lampung Tengah',
  'Lampung Timur',
  'Lampung Utara',
  'Mesuji',
  'Pesawaran',
  'Pringsewu',
  'Tanggamus',
  'Tulang Bawang',
  'Tulang Bawang Barat',
  'Bandar Lampung',
  'Metro',
  // Kepulauan Bangka Belitung
  'Bangka',
  'Bangka Barat',
  'Bangka Selatan',
  'Bangka Tengah',
  'Belitung',
  'Belitung Timur',
  'Pangkal Pinang',
  // Kepulauan Riau
  'Bintan',
  'Karimun',
  'Kepulauan Anambas',
  'Lingga',
  'Natuna',
  'Batam',
  'Tanjung Pinang',
  // DKI Jakarta
  'Jakarta Barat',
  'Jakarta Pusat',
  'Jakarta Selatan',
  'Jakarta Timur',
  'Jakarta Utara',
  'Kepulauan Seribu',
  // Jawa Barat
  'Bandung',
  'Bandung Barat',
  'Bekasi',
  'Bogor',
  'Ciamis',
  'Cianjur',
  'Cirebon',
  'Garut',
  'Indramayu',
  'Karawang',
  'Kuningan',
  'Majalengka',
  'Pangandaran',
  'Purwakarta',
  'Subang',
  'Sukabumi',
  'Sumedang',
  'Tasikmalaya',
  'Bandung Kota',
  'Bekasi Kota',
  'Bogor Kota',
  'Cirebon Kota',
  'Depok',
  'Sukabumi Kota',
  'Tasikmalaya Kota',
  // Jawa Tengah
  'Banjarnegara',
  'Banyumas',
  'Batang',
  'Blora',
  'Boyolali',
  'Brebes',
  'Cilacap',
  'Demak',
  'Grobogan',
  'Jepara',
  'Karanganyar',
  'Kebumen',
  'Kendal',
  'Klaten',
  'Kudus',
  'Kulon Progo',
  'Magelang',
  'Magelang Kota',
  'Pati',
  'Pekalongan',
  'Pekalongan Kota',
  'Pemalang',
  'Purbalingga',
  'Purwodadi',
  'Purworejo',
  'Rembang',
  'Salatiga',
  'Semarang',
  'Semarang Kota',
  'Sragen',
  'Sukoharjo',
  'Sleman',
  'Surakarta',
  'Tegal',
  'Tegal Kota',
  'Temanggung',
  'Wonogiri',
  'Wonosobo',
  // DI Yogyakarta
  'Bantul',
  'Gunung Kidul',
  'Yogyakarta',
  // Jawa Timur
  'Bangkalan',
  'Banyuwangi',
  'Blitar',
  'Blitar Kota',
  'Bojonegoro',
  'Bondowoso',
  'Gresik',
  'Jember',
  'Jombang',
  'Kediri',
  'Kediri Kota',
  'Kepulauan Madura',
  'Lamongan',
  'Lumajang',
  'Madiun',
  'Madiun Kota',
  'Magetan',
  'Malang',
  'Malang Kota',
  'Mojokerto',
  'Mojokerto Kota',
  'Nganjuk',
  'Ngawi',
  'Pacitan',
  'Pamekasan',
  'Pasuruan',
  'Pasuruan Kota',
  'Ponorogo',
  'Probolinggo',
  'Probolinggo Kota',
  'Sampang',
  'Sidoarjo',
  'Situbondo',
  'Sumenep',
  'Surabaya',
  'Trenggalek',
  'Tuban',
  'Tulungagung',
  // Bali
  'Badung',
  'Bangli',
  'Buleleng',
  'Gianyar',
  'Jembrana',
  'Karangasem',
  'Klungkung',
  'Tabanan',
  'Denpasar',
  // Nusa Tenggara Barat
  'Bima',
  'Bima Kota',
  'Dompu',
  'Lombok Barat',
  'Lombok Tengah',
  'Lombok Timur',
  'Lombok Utara',
  'Mataram',
  'Sumbawa',
  'Sumbawa Barat',
  // Nusa Tenggara Timur
  'Alor',
  'Ambon',
  'Belu',
  'Flores Timur',
  'Kupang',
  'Kupang Kota',
  'Lembata',
  'Maluku Barat Daya',
  'Maluku Tengah',
  'Maluku Tenggara',
  'Maluku Tenggara Barat',
  'Manggarai',
  'Manggarai Barat',
  'Manggarai Timur',
  'Ngada',
  'Rote Ndao',
  'Sabu Raijua',
  'Sikka',
  'Sumba Barat',
  'Sumba Barat Daya',
  'Sumba Timur',
  'Sumba Tengah',
  'Timor Tengah Selatan',
  'Timor Tengah Utara',
  // Kalimantan Barat
  'Bengkayang',
  'Capuas',
  'Kayong Utara',
  'Ketapang',
  'Kubu Raya',
  'Landak',
  'Mempawah',
  'Pontianak',
  'Pontianak Kota',
  'Sambas',
  'Sanggau',
  'Sekadau',
  'Sintang',
  // Kalimantan Tengah
  'Barito Selatan',
  'Barito Timur',
  'Barito Utara',
  'Gunung Mas',
  'Kapuas',
  'Katingan',
  'Kotawaringin Barat',
  'Kotawaringin Timur',
  'Lamandau',
  'Murung Raya',
  'Palangka Raya',
  'Pulang Pisau',
  'Sukamara',
  'Seruyan',
  // Kalimantan Selatan
  'Balangan',
  'Banjar',
  'Banjar Kota',
  'Barito Kuala',
  'Hulu Sungai Selatan',
  'Hulu Sungai Tengah',
  'Hulu Sungai Utara',
  'Kotabaru',
  'Tabalong',
  'Tanah Bumbu',
  'Tanah Laut',
  'Banjarmasin',
  'Banjarbaru',
  // Kalimantan Timur
  'Berau',
  'Bulungan',
  'Kutai Barat',
  'Kutai Kartanegara',
  'Kutai Timur',
  'Malinau',
  'Nunukan',
  'Pasir',
  'Penajam Paser Utara',
  'Penajam Paser Utara Kota',
  'Samarinda',
  'Tarakan',
  // Kalimantan Utara
  'Tana Tidung',
  // Sulawesi Utara
  'Bolaang Mongondow',
  'Bolaang Mongondow Selatan',
  'Bolaang Mongondow Timur',
  'Bolaang Mongondow Utara',
  'Kepulauan Sangihe',
  'Kepulauan Talaud',
  'Manado',
  'Minahasa',
  'Minahasa Selatan',
  'Minahasa Tenggara',
  'Minahasa Utara',
  'Tomohon',
  // Sulawesi Tengah
  'Banggai',
  'Banggai Kepulauan',
  'Banggai Laut',
  'Buol',
  'Donggala',
  'Morowali',
  'Morowali Utara',
  'Parigi Moutong',
  'Poso',
  'Sigi',
  'Tojo Una-Una',
  'Toli-Toli',
  'Palu',
  // Sulawesi Selatan
  'Bantaeng',
  'Barru',
  'Bone',
  'Bulukumba',
  'Enrekang',
  'Gowa',
  'Jeneponto',
  'Kepulauan Selayar',
  'Luwu',
  'Luwu Timur',
  'Luwu Utara',
  'Makassar',
  'Maros',
  'Palopo',
  'Parepare',
  'Pinrang',
  'Sidenreng Rappang',
  'Sinjai',
  'Soppeng',
  'Takalar',
  'Tana Toraja',
  'Tana Toraja Utara',
  'Toraja Utara',
  'Wajo',
  // Sulawesi Tenggara
  'Bombana',
  'Buton',
  'Buton Selatan',
  'Buton Tengah',
  'Buton Utara',
  'Kolaka',
  'Kolaka Timur',
  'Kolaka Utara',
  'Konawe',
  'Konawe Kepulauan',
  'Konawe Selatan',
  'Konawe Utara',
  'Muna',
  'Muna Barat',
  'Wakatobi',
  'Bau-Bau',
  'Kendari',
  // Gorontalo
  'Boalemo',
  'Bone Bolango',
  'Gorontalo',
  'Gorontalo Utara',
  'Pohuwato',
  'Gorontalo Kota',
  // Maluku
  'Ambon',
  'Buru',
  'Buru Selatan',
  'Kepulauan Aru',
  'Kepulauan Tanimbar',
  'Maluku Barat Daya',
  'Maluku Tengah',
  'Maluku Tenggara',
  'Maluku Tenggara Barat',
  'Seram Bagian Barat',
  'Seram Bagian Timur',
  'Tual',
  // Maluku Utara
  'Halmahera Barat',
  'Halmahera Selatan',
  'Halmahera Tengah',
  'Halmahera Timur',
  'Halmahera Utara',
  'Kepulauan Morotai',
  'Pulau Morotai',
  'Ternate',
  'Tidore Kepulauan',
  // Papua Barat
  'Arfak',
  'Fakfak',
  'Kaimana',
  'Manokwari',
  'Manokwari Selatan',
  'Maybrat',
  'Pegunungan Arfak',
  'Raja Ampat',
  'Sorong',
  'Sorong Selatan',
  'Sorong Kota',
  'Tambrauw',
  'Teluk Bintuni',
  'Teluk Wondama',
  // Papua
  'Asmat',
  'Biak Numfor',
  'Biak Timur',
  'Dogiyai',
  'Intan Jaya',
  'Jayapura',
  'Jayapura Kota',
  'Jayawijaya',
  'Kerom',
  'Keerom',
  'Lanny Jaya',
  'Mamberamo Raya',
  'Mamberamo Tengah',
  'Mappi',
  'Merauke',
  'Mimika',
  'Nabire',
  'Nduga',
  'Paniai',
  'Pegunungan Bintang',
  'Puncak',
  'Puncak Jaya',
  'Sarmi',
  'Supiori',
  'Tolikara',
  'Waropen',
  'Yahukimo',
  'Yalimo',
  // Papua Selatan
  'Boven Digoel',
  'Bade',
  // Papua Tengah
  // (entries already included above)
];

// Export deduped list preserving first occurrence order
export const INDONESIAN_DISTRICTS = Array.from(
  new Set(_RAW_INDONESIAN_DISTRICTS)
);

// Country Codes (unchanged)
export const COUNTRY_CODES = [
  { code: '+62', flag: '🇮🇩', country: 'Indonesia' },
  { code: '+1', flag: '🇺🇸', country: 'United States' },
  { code: '+44', flag: '🇬🇧', country: 'United Kingdom' },
  { code: '+61', flag: '🇦🇺', country: 'Australia' },
  { code: '+81', flag: '🇯🇵', country: 'Japan' },
  { code: '+86', flag: '🇨🇳', country: 'China' },
  { code: '+91', flag: '🇮🇳', country: 'India' },
  { code: '+33', flag: '🇫🇷', country: 'France' },
  { code: '+49', flag: '🇩🇪', country: 'Germany' },
  { code: '+39', flag: '🇮🇹', country: 'Italy' },
  { code: '+34', flag: '🇪🇸', country: 'Spain' },
  { code: '+31', flag: '🇳🇱', country: 'Netherlands' },
  { code: '+46', flag: '🇸🇪', country: 'Sweden' },
  { code: '+47', flag: '🇳🇴', country: 'Norway' },
  { code: '+45', flag: '🇩🇰', country: 'Denmark' },
  { code: '+358', flag: '🇫🇮', country: 'Finland' },
  { code: '+41', flag: '🇨🇭', country: 'Switzerland' },
  { code: '+43', flag: '🇦🇹', country: 'Austria' },
  { code: '+32', flag: '🇧🇪', country: 'Belgium' },
  { code: '+60', flag: '🇲🇾', country: 'Malaysia' },
  { code: '+65', flag: '🇸🇬', country: 'Singapore' },
  { code: '+66', flag: '🇹🇭', country: 'Thailand' },
  { code: '+84', flag: '🇻🇳', country: 'Vietnam' },
  { code: '+63', flag: '🇵🇭', country: 'Philippines' },
];
